services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jpa-demo
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "8081:5432"

#  maildev:
#    image: maildev/maildev
#    ports:
#      - "1080:1080"
#      - "1025:1025"